Functionality to retrieve Service Reference from Service
CppMicroServices/CppMicroServices pull request #1044
Opened 2024-10-04 17:27 UTC by tcormackMW

2024-10-09 12:31 UTC, jeffdiclemente requested changes
please add a RFC for this to the rfcs repo. Thanks!

2024-10-09 12:31 UTC, jeffdiclemente commented on framework/src/service/ServiceReferenceBasePrivate.h
> +    struct ServiceHolder
`ServiceHolder` and `UngetHelper` enable the same behavior for two different use cases (singleton service vs. bundle/prototype service). Now that these classes are in the same file, does it make sense to combine these two classes into one class that handles both use cases?

Combining these classes isn't required and I am fine with doing this at a later time if its possible and desirable.

2024-10-09 13:52 UTC, carneyweb commented on framework/src/service/ServiceReferenceBasePrivate.h
> +            delete sh;
However, it's ALWAYS safe to delete a nullptr in c++: https://stackoverflow.com/questions/4190703/is-it-safe-to-delete-a-null-pointer

2024-10-09 13:58 UTC, carneyweb commented on framework/src/service/ServiceReferenceBasePrivate.h
> +            delete uh;
it's ALWAYS safe to delete a nullptr in c++: https://stackoverflow.com/questions/4190703/is-it-safe-to-delete-a-null-pointer

The delete operator does the nullptr check itself. Adding a check to the code just clutters things needlessly.

2024-10-09 14:00 UTC, Burgch reviewed
Looking good, thanks Toby! +1 to Jeff's comments too :)

2024-10-09 14:00 UTC, Burgch commented on framework/src/service/ServiceReferenceBasePrivate.cpp
> +            throw std::runtime_error("Not a managed shared_ptr");
Could add test coverage of this by confirming that this throws if you pass in a `shared_ptr` you've created yourself in the test?

2024-10-09 14:00 UTC, tcormackMW commented on framework/src/service/ServiceReferenceBasePrivate.h
> +            delete sh;
Also, given that we are the one creating the ServiceHolder, and only the deleter for the actual object is invoked (ie ServiceHolder when it is a shared_ptr<ServiceHolder> and UngetHelper when it is a shared_ptr<UngetHelper), that pointer will never be null... right?

2024-10-09 14:04 UTC, carneyweb commented on framework/src/service/ServiceReferenceBasePrivate.h
> +        ServiceHolder<void> const* const sh_;
This is just a matter of coding style and personal preference... but I personally really dislike naming member variables with the trailing underscore. I find that it makes reading code like "ah_->do_something()" with the "_->" awkward to read. If we really need to name a member variable in a special way to mark it as such, I prefer using the "m_ah" form. The code doesn't look strange and the "m_" is very visible... more so than a trailing "_".

For what it's worth :-)

2024-10-09 14:06 UTC, carneyweb approved these changes

2024-10-09 20:09 UTC, Burgch approved these changes
LGTM, thanks Toby!

2024-10-11 16:11 UTC, Burgch approved these changes
LGTM 😃

2024-10-11 18:10 UTC, jeffdiclemente approved these changes
I think there is one testpoint missing that would be useful to lockdown the behavior of a `ServiceReference`. Other than that, LGTM and if you agree with me, I don't need to re-review after adding another testpoint.

2024-10-11 18:10 UTC, jeffdiclemente commented on compendium/DeclarativeServices/test/gtest/TestServiceReferenceRetrieval.cpp
> +    TEST_F(tServiceComponent, testServiceReferenceRetrievalForDSAndManReg)
this is a good set of testpoints. I think there is one case missing; what happens if you:
1. register a service, say `foo`
2. get a service ref to `foo`
3. get an instance of the service object `foo`
4. call `cppmicroservices::ServiceReferenceFromService` passing in the `foo` from step 3
5. unregister `foo` with the cppms framework

What is the expected state of the service ref returned by `cppmicroservices::ServiceReferenceFromService`? I would expect it to act the same as any other service ref that had its service unregistered with the cppms framework.

2024-10-11 19:29 UTC, merged