Namespace renaming tool
CppMicroServices/CppMicroServices pull request #1050
Opened 2024-12-04 17:12 UTC by Monika032

Following changes are to introduce tool to rename namespace of CppMicroServices codebase. 
Tool: change_namespace
Usage: change_namespace --cppms=<path to cppms sources> --namespace=<new_namespace_word> --namespace-alias (if we want to alias to the original namespace) <output_directory>

This tool will copy the all the files with namespace "cppmicroservices" replaced with the new word provided in the output directory. 

Signed-off-by: The MathWorks, Inc. [mphadnis@mathworks.com](mailto:mphadnis@mathworks.com)

2024-12-05 13:00 UTC, jeffdiclemente reviewed
there needs to be tests for this tool.

2024-12-05 13:00 UTC, jeffdiclemente commented on tools/change_namespace/AddPaths.cpp
> +   while(i != j)
please use a range-based for loop

2024-12-05 13:00 UTC, jeffdiclemente commented on tools/change_namespace/AddPaths.cpp
> +    while (i != j)
can a range-based for loop be used instead?

2024-12-05 13:00 UTC, jeffdiclemente commented on tools/change_namespace/AddPaths.cpp
> +            if (discard_message.size())
I recommend using an if-with initializer statement here, see https://skebanga.github.io/if-with-initializer/ for details. It helps to tightly scope variable use to within the if statement.

2024-12-05 13:00 UTC, jeffdiclemente commented on tools/change_namespace/FileHandler.cpp
> +bool      FileHandler::empty() const
minor: formatting

2024-12-17 12:53 UTC, kkumar45 commented on tools/change_namespace/AddPaths.cpp
> +   fs::directory_iterator i(m_cppms_path / p);
Should be use descriptive variable names for better readability and maintainability?

2024-12-17 12:53 UTC, kkumar45 commented on tools/change_namespace/ChangeNamespace.hpp
> +typedef std::shared_ptr<CNApplication> cn_app_ptr;
please use `using` for `typedef`

2024-12-17 12:53 UTC, kkumar45 commented on tools/change_namespace/ChangeNamespaceImpl.hpp
> +   void add_path(const fs::path& p);
It would be good to add documentation for functions and classes as applicable.

2024-12-27 10:41 UTC, kkumar45 commented
Does this tool also changes the final library names as per the new namespace? The usage is not very clear to me. Can you please also add the brief purpose of this tool in top sign-off section?

2025-01-17 07:21 UTC, Monika032 commented on tools/change_namespace/test/ChangeNamespaceTest.cpp
> +#include <gtest/gtest.h>
The header is found on execution - false warning.

2025-01-17 07:22 UTC, Monika032 commented on tools/change_namespace/main.cpp
> +        switch (opt.index())
we are covering all cases with separate conditionals.

2025-01-17 07:29 UTC, Monika032 commented on tools/change_namespace/main.cpp
> +const option::Descriptor usage[] = {
optionparser APIs use C-style arrays, thus not modifying usage array.

2025-02-10 09:40 UTC, kkumar45 commented on tools/change_namespace/CopyPaths.cpp
> +        static std::vector<char> v1, v2;
what is the purpose of static keyword? can we use string instead of vector<char> ?

2025-02-10 09:46 UTC, kkumar45 commented on tools/change_namespace/main.cpp
> +            case CPPMS:
if this is used for location, then can we change it to "--src"?

2025-02-21 18:47 UTC, Monika032 commented on tools/change_namespace/ChangeNamespace.hpp
> +using cn_app_ptr = std::shared_ptr<CNApplication>;
Changed to unique_ptr.

2025-02-21 18:51 UTC, Monika032 commented on tools/change_namespace/CopyPaths.cpp
> +    // Simply copy the files under the tools/change_namespace directory (own sources)
Removed copying tools sources.

2025-02-21 18:51 UTC, Monika032 commented on tools/change_namespace/CopyPaths.cpp
> +    if (m_namespace_name.size() && (is_source_file(p) || is_test_config_file(p)))
Refactored the code.

2025-02-21 18:52 UTC, Monika032 commented on tools/change_namespace/PathUtility.cpp
> +    std::string const& as = a.generic_string();
Moved this operation to the custom comparator definition with modern APIs.

2025-02-21 18:53 UTC, Monika032 commented on tools/change_namespace/main.cpp
> +            case CPPMS:
added src word to the tool option to make it evident we are providing cppms source path.

2025-02-21 18:54 UTC, Monika032 commented on tools/change_namespace/ChangeNamespace.hpp
> +  public:
My initial idea was to separate interface and implementation. But considering we may not use this interface for any new usecases, it may not be required. 
@jeffdiclemente What do you suggest should we remove the interface type design?

2025-03-18 05:17 UTC, Monika032 commented on tools/change_namespace/ChangeNamespace.hpp
> +  public:
Removed the interface - ChangeNamespace is simple class now.

2025-03-18 05:48 UTC, Monika032 commented on tools/jsonschemavalidator/cmake_install.cmake
These got added by mistake. Removing this and other Cmake generated files.

2025-03-25 07:42 UTC, Monika032 commented on tools/change_namespace/FileHandler.cpp
> +FileHandler::operator=(FileHandler const& that)
Removed FileHandler class.

2025-03-25 07:42 UTC, Monika032 commented on tools/change_namespace/FileHandler.cpp
> +FileHandler::operator=(FileHandler const& that)
Removed Filehandler class.

2025-03-25 07:49 UTC, Monika032 commented on tools/change_namespace/test/ChangeNamespaceTest.cpp
> +        std::string command = exePath + " --cppms=" + inputFile +
command is initialized.

2025-03-25 08:07 UTC, Monika032 commented on tools/change_namespace/ChangeNamespace.hpp
> +class CNApplication
Removed CNApplication interface.

2025-03-25 08:08 UTC, Monika032 commented on tools/change_namespace/test/ChangeNamespaceTest.cpp
> +    const std::string exePath = EXE_PATH; // Path to the executable being tested
Using EXE_PATH directly

2025-03-27 08:56 UTC, Monika032 commented on tools/change_namespace/main.cpp
> +   std::list<const char*> positional_args;
Code replaced with optionparser.

2025-03-27 08:56 UTC, Monika032 commented on tools/change_namespace/main.cpp
> +   for(int i = 1; i < argc; ++i)
Code replaced with optionparser.

2025-03-27 08:57 UTC, Monika032 commented on tools/change_namespace/main.cpp
> +       std::cout << "Error: Please provide all required arguments. " << std::endl;
Code replaced with optionparser.

2025-05-20 14:36 UTC, jeffdiclemente requested changes

2025-05-20 14:36 UTC, jeffdiclemente commented on tools/change_namespace/main.cpp
> +    printError(std::string const& msg1, option::Option const& opt, std::string const& msg2)
is this function necessary given it only has one call site?

2025-05-21 07:07 UTC, Monika032 commented on CMakeLists.txt
> +if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/tools/change_namespace)
So when we run this tool on source code and it creates a full copy of all files with replaced namespace - we are not copying tools/change_namespace code. It made less sense to have the tool code in replaced namespace code since we already ran it. That's why the build checks for its existence.

2025-05-21 07:10 UTC, Monika032 commented on tools/change_namespace/main.cpp
> +    printError(std::string const& msg1, option::Option const& opt, std::string const& msg2)
Even though we see single call site but this custom arg + method is being defined to configure non-empty (compulsory) arguments in the optionparser. printError will be invoked any time user doesn't provide a required argument.

2025-05-21 15:14 UTC, jeffdiclemente approved these changes
LGTM. please make sure to update this branch with the latest from the development branch and resolve the .yml files to use the development branch versions. Thanks!

2025-07-04 06:39 UTC, merged