Service Scope
CppMicroServices/CppMicroServices pull request #1054
Opened 2024-12-18 14:14 UTC by tcormackMW

with to references to prototype services. Also added test cases that validate proper behavior for references to both singleton and prototype services.

2024-12-18 14:18 UTC, tcormackMW commented
Verify what we do for bundle scoped (whether this defaults to singleton or prototype

2024-12-19 17:20 UTC, jeffdiclemente requested changes

2024-12-19 17:20 UTC, jeffdiclemente commented on compendium/DeclarativeServices/src/ComponentContextImpl.cpp
> +                                      }
I think this entire block can be simplified significantly and that the reference scope of the service reference doesn't need to be queried at all based off of the documentation for `ServiceObjects` class. `ServiceObjects` should do the right thing already based on the scope of the service.

2024-12-23 14:59 UTC, carneyweb commented on compendium/test_bundles/TestBundleDSFAC1/src/ServiceImpl.hpp
> +        void*
Done.

2024-12-23 15:01 UTC, carneyweb commented on compendium/test_bundles/TestBundleDSFAC1/src/ServiceImpl.hpp
> +        void*
Done.

2024-12-23 15:01 UTC, carneyweb commented on compendium/test_bundles/TestBundleDSFAC1/src/ServiceImpl.hpp
> +        void*
Done.

2024-12-23 15:01 UTC, carneyweb commented on compendium/DeclarativeServices/test/gtest/TestComponentContextImpl.cpp
> +#if NEVER
Done.

2024-12-23 17:47 UTC, jeffdiclemente approved these changes

2024-12-30 15:12 UTC, tcormackMW commented
> Verify what we do for bundle scoped (whether this defaults to singleton or prototype)

@jeffdiclemente It looks like this doesn't matter anymore because we rely on GetService to return the 'correct' thing based on the scope of the service. 

For the sake of figuring this question out anyway, we treat BUNDLE_SCOPE as PROTOTYPE_SCOPE in the codebase.

2024-12-30 15:15 UTC, merged