Scope file handles to BundleResource and BundleResourceStream life-times, resolves #309
CppMicroServices/CppMicroServices pull request #390
Opened 2019-09-26 15:27 UTC by achristoforides

This PR introduces changes which resolve issue #309 .

Instead of closing BundleResource file handles at the end of the Bundle life-time, they are now cleaned up if there are no opened resources in a given bundle/bundle container. To achieve this, a reference counting method is used to keep track of how many opened resources there are associated with the given bundle. If this number reaches 0, then the container is closed (thus closing the file handles). If a user requests a resource after the bundle has been closed, it is then reopened and their resource is then served all while keeping track of the reference count.

2019-10-01 11:30 UTC, jeffdiclemente requested changes
Tests need to be added to ```framework\test\gtest\OpenFileHandleTest.cpp``` for this new behavior.

2019-10-04 14:21 UTC, jeffdiclemente requested changes

2019-10-04 14:21 UTC, jeffdiclemente commented on framework/src/bundle/BundlePrivate.cpp
> +  barchive->GetResourceContainer()->CloseContainer();
This should be removed.

2019-10-04 17:20 UTC, jeffdiclemente approved these changes

2019-10-11 15:05 UTC, jeffdiclemente approved these changes

2019-10-11 15:29 UTC, jeffdiclemente commented
@saschazelzer do you have any flags for this? If not i'm planning on merging this in on Monday. Thanks.

2019-10-15 11:41 UTC, jeffdiclemente requested changes
I looked over the code one more time and noticed a couple things.

2019-10-15 11:41 UTC, jeffdiclemente commented on framework/src/bundle/BundleArchive.cpp
> +  }
This isn't necessary since constructing the ```BundleResource``` will call ```OpenContainer()``` if necessary.

2019-10-15 11:41 UTC, jeffdiclemente commented on framework/src/bundle/BundleArchive.cpp
> +  }
This isn't necessary since constructing the ```BundleResource``` will call ```OpenContainer()``` if necessary.

2019-10-15 15:04 UTC, jeffdiclemente requested changes

2019-10-15 15:04 UTC, jeffdiclemente commented on framework/src/bundle/BundleResource.cpp
> +      this->archive->resourceContainer->OpenContainer();
This can be removed. Constructing ```BundleResource``` will open the container if necessary.

2019-10-16 14:46 UTC, jeffdiclemente approved these changes

2019-10-22 11:30 UTC, jeffdiclemente requested changes
The code coverage failure can be solved with a slightly different solution. If the default member initialization of numOpenResources is moved to the constructor and the friend classes are removed, at least locally on my machine, this fixes the code coverage error.

I still don't know why this solves the issue though.

My next step is to isolate the friend class change and see if that causes the same code coverage failure.

2019-10-22 12:49 UTC, jeffdiclemente commented
> The gcov failure can be solved with a slightly different solution. If the default member initialization of numOpenResources is moved to the constructor and the friend classes are removed, at least locally on my machine, this fixes the gcov error.
> 
> I still don't know why this solves the issue though.
> 
> My next step is to isolate the friend class change and see if that causes the same gcov failure.

adding back the friend class (and not the default member initialization of numOpenResources) does **not** produce the same gcov file containing ~20 lines containing ```/*EOF*/``` (which ultimately leads to cmake failing).

2019-10-22 16:41 UTC, jeffdiclemente requested changes

2019-10-22 16:41 UTC, jeffdiclemente commented on framework/src/bundle/BundleResource.cpp
> +    if (this->archive->GetNumOpenResources() == 0)
single line if statement should still have braces.

2019-10-22 17:58 UTC, jeffdiclemente requested changes

2019-10-22 17:58 UTC, jeffdiclemente commented on framework/src/bundle/BundleArchive.h
> +  mutable unsigned int numOpenResources;
this should be an ```atomic<uint32_t>``` since a race can occur if more than one thread tries to create ```BundleResource``` object.

2019-10-22 17:58 UTC, jeffdiclemente commented on framework/src/bundle/BundleResource.cpp
> +    }
move this logic into the ```DecrementNumOpenResources()``` and either rename the function or document it to reflect the behavior.

2019-10-22 18:56 UTC, jeffdiclemente requested changes

2019-10-22 18:56 UTC, jeffdiclemente commented on framework/src/bundle/BundleArchive.h
> +  unsigned int GetNumOpenResources() const;
```GetNumOpenResources()``` isn't needed anymore. it can be removed.

2019-10-22 18:56 UTC, jeffdiclemente commented on framework/src/bundle/BundleArchive.cpp
> +  if (numOpenResources == 0) {
there is a race between lines 157 and 158 where one thread can decrement ```numOpenResources``` and before it executes line 158 another thread executes line 157. Even within line 158 there is a race between the time it takes to retrieve the value in ```numOpenResources``` and compare it to ```0```. The race can be solved by using https://en.cppreference.com/w/cpp/atomic/atomic/compare_exchange or by adding a mutex around the increment, decrement and comparison of ```numOpenResources``` (in which case you don't need to use ```std::atomic```).

2019-10-23 11:27 UTC, jeffdiclemente reviewed
performance should be measured within the google benchmark tests to see what the overhead is now that a mutex has been introduced.

2019-10-23 11:27 UTC, jeffdiclemente approved these changes

2019-10-23 16:36 UTC, jeffdiclemente commented
> performance should be measured within the google benchmark tests to see what the overhead is now that a mutex has been introduced.

I ran the two bundle install benchmarks against development and this branch. Here are the results:

Benchmark Test  | development Time   | development CPU   | achristoforides:309-scope-file-handle Time | achristoforides:309-scope-file-handle CPU 
------------------- | ---------- | ---------- | ---------- | --------------|
BundleInstallFixture/BundleInstallCppFramework/manual_time_mean  |     274950 ns  |     331298 ns   |      284231 ns   |    342625 ns
BundleInstallFixture/BundleInstallCppFramework/manual_time_median  |   273459 ns   |    328281 ns  |       282698 ns     |  339929 ns
BundleInstallFixture/BundleInstallCppFramework/manual_time_stddev    |  17049 ns   |     19412 ns   |      17422 ns      |  19760 ns
BundleInstallFixture/LargeBundleInstallCppFramework/manual_time_mean   |    271779 ns   |    336457 ns    |      276112 ns     |  333663 ns
BundleInstallFixture/LargeBundleInstallCppFramework/manual_time_median  |   269830 ns  | 335545 ns     |    274588 ns    |   331362 ns
BundleInstallFixture/LargeBundleInstallCppFramework/manual_time_stddev   |   16674 ns   |  19432 ns  |    15395 ns    |    17959 ns

2019-10-24 18:07 UTC, jeffdiclemente commented
I'd like to hold off on merging this for now. This change does regress bundle install performance which I believe is important.

2019-11-21 01:27 UTC, achristoforides commented
| Benchmark Test                                                         | development Time | development CPU | achristoforides:309-scope-file-handle Time | achristoforides:309-scope-file-handle CPU |
|------------------------------------------------------------------------|------------------|-----------------|--------------------------------------------|-------------------------------------------|
| BundleInstallFixture/BundleInstallCppFramework/manual_time_mean        | 158891 ns        | 175477 ns       | 157877 ns                                  | 175230 ns                                 |
| BundleInstallFixture/BundleInstallCppFramework/manual_time_median      | 158668 ns        | 175203 ns       | 157544 ns                                  | 174824 ns                                 |
| BundleInstallFixture/BundleInstallCppFramework/manual_time_stddev      | 1474 ns          | 1651 ns         | 1646 ns                                    | 1833 ns                                   |
| BundleInstallFixture/LargeBundleInstallCppFramework/manual_time_mean   | 163047 ns        | 180998 ns       | 161200 ns                                  | 178758 ns                                 |
| BundleInstallFixture/LargeBundleInstallCppFramework/manual_time_median | 162577 ns        | 180516 ns       | 160931 ns                                  | 178499 ns                                 |
| BundleInstallFixture/LargeBundleInstallCppFramework/manual_time_stddev | 1524 ns          | 1719 ns         | 1533 ns                                    | 1702 ns                                   |

I updated this PR by removing the mutex in BundleArchive and replacing it with a std::atomic implementation. The results in this table were generated by running the benchmark test with --benchmark_repetitions=256. As you can see, the timings are actually better compared to what they were before this change.

2019-11-21 14:45 UTC, jeffdiclemente requested changes

2019-11-21 14:45 UTC, jeffdiclemente commented on framework/src/bundle/BundleArchive.cpp
>      resourceContainer->CloseContainer();
unfortunately there's still a race between the time in which ```numOpenResources``` is atomically set and when it is evaluated by the if statement.

2019-11-21 16:39 UTC, achristoforides commented
| Benchmark Test                                                         | development Time | development CPU | achristoforides:309-scope-file-handle Time | achristoforides:309-scope-file-handle CPU |
|------------------------------------------------------------------------|------------------|-----------------|--------------------------------------------|-------------------------------------------|
| BundleInstallFixture/BundleInstallCppFramework/manual_time_mean        | 395675 ns        | 450865 ns       | 399481 ns                                  | 451873 ns                                 |
| BundleInstallFixture/BundleInstallCppFramework/manual_time_median      | 374271 ns        | 439257 ns       | 371490 ns                                  | 442217 ns                                 |
| BundleInstallFixture/BundleInstallCppFramework/manual_time_stddev      | 46192 ns         | 56893 ns        | 50370 ns                                   | 64054 ns                                  |
| BundleInstallFixture/LargeBundleInstallCppFramework/manual_time_mean   | 388965 ns        | 454660 ns       | 402515 ns                                  | 453679 ns                                 |
| BundleInstallFixture/LargeBundleInstallCppFramework/manual_time_median | 367462 ns        | 443154 ns       | 378240 ns                                  | 442913 ns                                 |
| BundleInstallFixture/LargeBundleInstallCppFramework/manual_time_stddev | 47679 ns         | 59251 ns        | 51271 ns                                   | 66591 ns                                  |

Newly ran test (release mode, 512 iterations) comparing the mutex implementation vs. the development branch.

2026-08-15 02:12 UTC, closed without merging