Remove Bundle Threads
CppMicroServices/CppMicroServices pull request #533
Opened 2021-03-22 15:35 UTC by achristoforides

This PR removes BundleThreads from CppMicroServices.

BundleThread.h and BundleThread.cpp are removed and areas of the code which previously used them to facilitate bundle operations have been modified.

2021-03-24 13:01 UTC, jeffdiclemente requested changes

2021-03-24 13:01 UTC, jeffdiclemente commented on framework/test/driver/ConcurrencyTest.cpp
This whole file can be deleted if it was only used to test bundlethreads.

2021-03-24 13:04 UTC, jeffdiclemente requested changes

2021-03-24 13:04 UTC, jeffdiclemente commented on framework/test/driver/BundleTest.cpp
> -void TestWaitOnBundleOperation()
delete the TestBundleWaitOnOperation bundle since it no longer has a purpose once this test is removed.

2021-03-24 14:46 UTC, kevinleeMW commented on framework/src/bundle/BundlePrivate.cpp
>      // 3:
update comments so we don't skip // 2

2021-03-24 17:25 UTC, pelliott-mathworks approved these changes

2021-03-25 13:59 UTC, jeffdiclemente requested changes

2021-03-25 13:59 UTC, jeffdiclemente commented on framework/src/bundle/BundlePrivate.cpp
> +    // Note: This step hass been removed with removal of BundleThread
if BundleThreads is being removed, it doesn't make sense to add comments that reference it. I'd suggest updating the comments as if BundleThreads doesn't exist.

2021-03-25 13:59 UTC, jeffdiclemente commented on framework/src/bundle/BundlePrivate.cpp
> +void BundlePrivate::SetStateInstalled(bool sendEvent,
I suggest removing the lock parameter completely from all the functions that used to need it because of BundleThreads.

2021-03-25 18:22 UTC, jeffdiclemente requested changes

2021-03-25 18:22 UTC, jeffdiclemente commented on framework/src/bundle/BundlePrivate.cpp
>      // 3:
you still want to remove this comment then re-number the remainder of the comments.

2021-03-25 19:32 UTC, jeffdiclemente approved these changes

2021-03-25 20:56 UTC, merged