Add Config policies tests
CppMicroServices/CppMicroServices pull request #538
Opened 2021-03-30 15:37 UTC by Jeeyuen-Rick

Signed-off-by: The MathWorks, Inc. rickyu@mathworks.com

2021-03-31 15:58 UTC, pelliott-mathworks requested changes

2021-03-31 15:58 UTC, pelliott-mathworks commented on compendium/DeclarativeServices/test/TestConfigPolicies.cpp
> +TEST_F(tServiceComponent, testOptionalConfigPolicyImmediateTrue) // DS_CAI_FTC_5
Not sure we're testing the right thing here. The test procedure says "Verify that the component can be satisfied even if the corresponding configuration object is not present and can use corresponding configuration object if present." 

So basically there should be two tests. One should show that if the configuration object is not present when the component instance is constructed, the component is constructed with no properties. The second test should show that if the configuration object is present when the component instance is constructed, it should be constructed with the properties. I would use immediate = true, configuration-policy="optional"  for both cases.
 
Test1 - Construct an instance once with no properties available. Use GetProperties to show that the properties in the component instance have default values. 
Test2 - Construct an instance the second time with a configuration object available. Use GetProperties to show that the component instance was constructed with the updated properties from the configuration object.

2021-03-31 15:58 UTC, pelliott-mathworks commented on compendium/DeclarativeServices/test/TestConfigPolicies.cpp
> +  compConfigs = dsRuntimeService->GetComponentConfigurationDTOs(compDescDTO);
Already did the GetComponentConfigurationDTOs in the last block of code. Don't need to do it again? Just check the state?

2021-03-31 15:58 UTC, pelliott-mathworks commented on compendium/DeclarativeServices/test/TestConfigPolicies.cpp
> +TEST_F(tServiceComponent, testIgnoreConfigPolicy) // DS_CAI_FTC_7
Not sure we're testing the right thing here. Test procedure says "Verify that component can always be satisfied and do not use the configuration object even if present." Should use immediate=true, configuration-policy="ignore". Two tests make sense. 
Test 1 - do not create a configuration object. Verify that the component instance is created with default properties. 
Test 2 - create the configuration object. Verify that the component instance is created with default properties, not the properties from the configuration object.

2021-04-07 17:45 UTC, pelliott-mathworks requested changes
Getting there! Just a couple of comments.

2021-04-07 17:45 UTC, pelliott-mathworks commented on compendium/DeclarativeServices/test/TestConfigPolicies.cpp
> +  // cause DS to construct the instance with the updated properties.
Comment not accurate?

2021-04-07 17:45 UTC, pelliott-mathworks commented on compendium/DeclarativeServices/test/TestConfigPolicies.cpp
> +    << "Component state should be ACTIVE";
I think what we want to show in this test is that the configuration properties are used when the component instance is constructed so the configuration object has to be created before this point. One way is to use immediate = false, start the bundle, create the configuration object and then get an instance. The second way to do it is to create the configuration object before you start the bundle.

2021-04-07 17:45 UTC, pelliott-mathworks commented on compendium/DeclarativeServices/test/TestConfigPolicies.cpp
> +  auto instanceProps = instance->GetProperties();
The reason the properties are correct is because the Modified method was called by configuration->Update. It doesn't prove that construction worked.

2021-04-07 17:45 UTC, pelliott-mathworks commented on compendium/DeclarativeServices/test/TestConfigPolicies.cpp
> +  // cause DS to construct the instance with the updated properties.
Comment not correct?

2021-06-03 18:45 UTC, jeffdiclemente commented
@pelliott-mathworks @Jeeyuen-Rick can this PR be closed (and not merged)?

2021-06-03 18:48 UTC, Jeeyuen-Rick commented
> @pelliott-mathworks @Jeeyuen-Rick can this PR be closed (and not merged)?

Yes, this can be closed and merged.

2021-06-03 18:52 UTC, jeffdiclemente commented
@Jeeyuen-Rick This can't be merged until the merge conflicts have been addressed. Also this PR is setup to be merged into the development branch which I don't think should be done since this contains tests for the config admin + DS integration which has not been merged into development.

2021-06-03 18:57 UTC, Jeeyuen-Rick commented
> @Jeeyuen-Rick This can't be merged until the merge conflicts have been addressed. Also this PR is setup to be merged into the development branch which I don't think should be done since this contains tests for the config admin + DS integration which has not been merged into development.

@jeffdiclemente Sorry for the typo. I meant you can close the PR and not merged. This has been merged in the configadmin_ds_integration branch.

2021-06-03 18:58 UTC, closed without merging