Enable ASAN for local testing
CppMicroServices/CppMicroServices pull request #546
Opened 2021-04-12 15:43 UTC by achristoforides

This PR introduces changes which enables ASAN when building locally on Windows, Mac, and Linux.

Mac and Linux only require the developer to turn on US_ENABLE_ASAN while Windows additionally requires the developer to specify the path to the runtime DLL for ASAN provided by Microsoft (typically "clang_rt.asan_dbg_dynamic-x86_x64.dll" or "clang_rt.asan_dynamic-x86_x64.dll").

2021-04-12 18:54 UTC, pelliott-mathworks approved these changes

2021-04-13 10:57 UTC, jeffdiclemente requested changes
Please update the build documentation in doc/src/build_instructions.rst to reflect the TSan and Asan build options. If there is anything special one needs to do on Windows, this would be the place to document it. Thanks.

2021-04-13 14:44 UTC, jeffdiclemente requested changes

2021-04-13 14:44 UTC, jeffdiclemente commented on CMakeLists.txt
> +us_cache_var(US_ASAN_USER_DLL "" STRING "Path to asan dll" ADVANCED)
if this variable is only for ASan support on Windows, I suggest making that explicit in the variable description. So something like "Path to Windows Asan DLL"

2021-04-13 16:35 UTC, jeffdiclemente approved these changes

2021-04-13 16:36 UTC, merged