Fix ListConfigurations returning empty config objects
CppMicroServices/CppMicroServices pull request #663
Opened 2022-05-04 11:59 UTC by jeffdiclemente

Per OSGi standard, ListConfigurations should only return config objects containing properties (i.e. not an empty config).

Signed-off-by: The MathWorks, Inc. <jdicleme@mathworks.com>

2022-05-04 12:20 UTC, pelliott-mathworks approved these changes

2022-05-04 12:23 UTC, pelliott-mathworks reviewed
Just wondering if you noticed one of the build configurations failed. The BuildAndTestOnWIndows

2022-05-04 12:52 UTC, jeffdiclemente commented
yes, I'm looking into it.

2022-05-04 13:31 UTC, jeffdiclemente commented
missing part of the fix. apparently I wrote the test but didn't actually fix the bug... oops.

2022-05-11 18:43 UTC, achristoforides requested changes

2022-05-11 18:43 UTC, achristoforides commented on compendium/DeclarativeServices/src/manager/ConfigurationManager.cpp
> +        if (config.size() > 0 && config.front()->GetChangeCount() > 0) {
Everything after `&&` is not necessary. ListConfigurations will not return configurations that are empty.

2022-05-12 14:30 UTC, merged