ListConfigurations fix for empty configuration objects.
CppMicroServices/CppMicroServices pull request #682
Opened 2022-06-15 19:30 UTC by pelliott-mathworks

ListConfigurations should include configuration objects with no properties as long as those configuration objects have been updated at least once. A configuration object that is created from metadata counts as an object that has been updated at least once. Signed-off-by: The MathWorks, Inc. <pelliott@mathworks.com>

2022-06-16 14:12 UTC, jeffdiclemente commented
I don't think this is the right approach. what happens if a config object has properties and then it's properties are removed?

2022-06-16 14:14 UTC, achristoforides commented
> I don't think this is the right approach. what happens if a config object has properties and then it's properties are removed?

Wouldn't this fall under the category "configuration objects with no properties as long as those configuration objects have been updated at least once"? Initially properties were present but then the configuration was updated to now have no properties (an update).

2022-06-16 14:21 UTC, achristoforides commented
> > > I don't think this is the right approach. what happens if a config object has properties and then it's properties are removed?
> > 
> > 
> > Wouldn't this fall under the category "configuration objects with no properties as long as those configuration objects have been updated at least once"? Initially properties were present but then the configuration was updated to now have no properties (an update).
> 
> Checking if the config object was updated at least once doesn't take into account removed properties, which is what we care about in the `ListConfigurations` method: `Only Configuration objects with non- null properties are considered current. That is, Configuration.getProperties() is guaranteed not to return null for each of the returned Configuration objects.`

And "null" in this case (since the OSGi spec is Java based) empty (e.g., the map is of size 0)?

2022-06-17 12:54 UTC, jeffdiclemente requested changes
The public API doxygen documentation for ListConfigurations (`compendium\CM\include\cppmicroservices\cm\ConfigurationAdmin.hpp`) needs an update to remove ambiguity. Specifically, I think that `Used to list all of the available configurations.` is too vague. What does `available` mean?

2022-06-17 13:42 UTC, jeffdiclemente requested changes

2022-06-17 13:52 UTC, pelliott-mathworks commented on compendium/ConfigurationAdmin/src/ConfigurationAdminImpl.cpp
> +                           1u);
AddConfigurations is only called in one place, CMBundleExtension.cpp when it reads the manifest.json file to process configuration objects. It is not part of the public interface so it's can't be called from user code.

2022-06-17 13:53 UTC, pelliott-mathworks commented on compendium/ConfigurationAdmin/test/TestConfigurationAdminImpl.cpp
> +  // properties) unless the configuration object has been updated.
No tests for that. Will add them.

2022-06-17 14:58 UTC, jeffdiclemente approved these changes

2022-06-17 16:31 UTC, merged