Performance improvement form `brian-performance` branch
CppMicroServices/CppMicroServices pull request #728
Opened 2022-09-23 18:50 UTC by achristoforides

Signed-off-by: The MathWorks, Inc. <alchrist@mathworks.com>

2022-09-23 19:18 UTC, jeffdiclemente requested changes

2022-09-23 19:18 UTC, jeffdiclemente commented on framework/src/util/Properties.cpp
> +const Any& Properties::Value(const std::string& key, bool matchCase) const
This function should be named something more descriptive, e.g. `RefToValue`, `ValueByRef`, etc...

2022-09-23 19:18 UTC, jeffdiclemente commented on framework/include/cppmicroservices/detail/Threads.h
> +template<class LockingStrategy = MutexLockingStrategy<std::recursive_mutex>,
this change requires more evaluation. I think this change is needed to support the changes in [framework/src/service/ServiceRegistrationBase.cpp](https://github.com/CppMicroServices/CppMicroServices/pull/728/files#diff-36be34fd05c509bdeed05610be9b89469c8d193ec6ce5431f47f6bfd468e4e72) and I'd like to understand why. Making the locking strategy use `recursive_mutex` is a significant change the locking strategy used within the core framework.

2022-09-23 19:18 UTC, jeffdiclemente commented on framework/src/service/ServiceReferenceBase.cpp
> +  return (!p->registration->bundle.expired());
`std::weak_ptr::expired` is racy (https://en.cppreference.com/w/cpp/memory/weak_ptr/expired).  I'm not sure whether this matters or not for this usage. need to evaluate more thoroughly.

2022-10-12 19:51 UTC, jeffdiclemente approved these changes

2022-10-12 19:51 UTC, jeffdiclemente commented on framework/src/util/Properties.h
> +  const Any& ValueByRef(const std::string& key, bool matchCase = false) const;
This should be renamed to `ValueByRef_unlocked` to follow the same convention as `Value_unlocked` to indicate that this function doesn't hold a lock.

2022-10-17 15:11 UTC, carneyweb approved these changes

2023-01-10 13:48 UTC, jeffdiclemente commented
It looks like the change in the scoping of the locks in `bool    ServiceReferenceBase::operator<(ServiceReferenceBase const& reference) const` from the PR causes a deadlock.

`d.load()->registration->properties.Lock();` is followed by a call to `reference.d.load()->registration->properties.Lock();`, which will deadlock if `d.load()->registration->properties` and `reference.d.load()->registration->properties` are the same object. This shouldn't never happen as there is a check to see if `d.load()->registration` == `reference.d.load()->registration` before entering the scoped block.

2023-01-13 11:57 UTC, merged