Update Chagelog for #845
CppMicroServices/CppMicroServices pull request #847
Opened 2023-05-04 15:25 UTC by ShivamNegi

2023-05-04 15:27 UTC, jeffdiclemente requested changes
v3.7.6 has already been released, this change needs to be part of the next release. you'll need to create a new section

2023-05-04 15:27 UTC, jeffdiclemente commented
also, add "[ci skip]" to the commit message in the future to avoid building and testing since it isn't necessary for this change.

2023-05-05 18:05 UTC, ShivamNegi commented
I have made the necessary modifications to the pull request and incorporated them within the 'Unreleased' section. Please let me know if the current format is appropriate or if any further adjustments are required.

2023-05-10 11:37 UTC, jeffdiclemente approved these changes

2023-05-10 13:02 UTC, merged