Fix #920 serviceTracker segfault on concurrent `tracker.Close()` and `framework.Stop()`
CppMicroServices/CppMicroServices pull request #922
Opened 2023-09-13 14:03 UTC by tcormackMW

2023-09-13 15:08 UTC, carneyweb approved these changes

2023-09-15 19:29 UTC, tcormackMW commented
@jeffdiclemente Why is `d` valid when `CheckValid()` fails?

`BundleContext.d` is set to nullptr in the destruction of a framework inside the thread spawned by `Stop()`. This occurs [here](https://github.com/CppMicroServices/CppMicroServices/blob/4fded15af69c1b4ffd53c51d8eb857d4842d08dc/framework/src/util/FrameworkPrivate.cpp#L94).

But, as we found out, Bundles do not have access to their trackers. i.e. the tracker's `BundleContext` is not invalidated when the framework's `BundleContext` is swapped out of the framework. And the `ServiceTracker` holds a `shared_ptr<ServiceTrackerPrivate> which has a `BundleContext` which has a `std::shared_ptr<BundleContextPrivate>`, thereby keeping that object alive even if invalid. 

So even though the base object, the `BundleContextPrivate` is invalid, it is still alive. And so I think if `ServiceTracker`s are the ones that are calling `GetLogSink()`, I don't see a scenario where the `d` (a std::shared_ptr<BundleContextPrivate>` will ever be invalid in that function call. 

We are deleting the `GetLogSink()` anyway, but now I understand why that other if statement is not catching anything.

2023-09-18 13:07 UTC, jeffdiclemente requested changes

2023-09-18 13:07 UTC, jeffdiclemente commented on framework/src/bundle/BundleResourceContainer.cpp
>          catch (std::exception const& ex)
`ex` can be removed since its not used. I'm surprised that the linux/macOs builds didn't fail with an "unused variable" warning.

2023-09-18 13:07 UTC, jeffdiclemente commented on framework/src/bundle/BundleResource.cpp
remove `return data;` and replace `auto data = ` with `return`.

2023-09-18 14:51 UTC, jeffdiclemente approved these changes

2023-09-18 15:00 UTC, merged