Fix Boost namespace Versioning - Allow Custom Boost library versioning
CppMicroServices/CppMicroServices pull request #939
Opened 2023-10-03 18:53 UTC by tcormackMW

This reverts the change from `namespace boost` to `namespace cppmsboost` as we have now changed Cmake infrastructure to allow for custom specification of Boost Library versioning

2023-10-05 11:16 UTC, jeffdiclemente commented
> This reverts the change from `namespace boost` to `namespace cppmsboost` as we have now changed Cmake infrastructure to allow for custom specification of Boost Library versioning

@tcormackMW  I would prefer not to revert the boost namespace change. This allows default building of cppmicroservices (i.e. no custom boost being used) to guarantee there are no namespace collisions with boost and other libraries using boost.

2023-10-05 18:05 UTC, tcormackMW commented
@jeffdiclemente Performance testing done locally. From what is clear through the noise, the runs that show high regression change every run -- i.e. inconsistent performance losses. The tests that go much faster are somewhat consistently faster. 

I think that these changes should not introduce regressions and I am guessing we will gain back some speed from these changes.

2023-10-06 12:45 UTC, jeffdiclemente requested changes
With absl being removed, its usage should be removed from framework\CMakeLists.txt

2023-10-10 13:09 UTC, jeffdiclemente approved these changes

2023-10-10 13:12 UTC, merged