noexecstack addition to CMakeLists
CppMicroServices/CppMicroServices pull request #994
Opened 2024-02-12 20:58 UTC by tcormackMW

2024-02-13 11:18 UTC, jeffdiclemente requested changes
looks like there are macos build failures to investigate as well.

2024-02-13 11:18 UTC, jeffdiclemente commented on CMakeLists.txt
> +# g3232705: Add flag to force non executable stack on gcc builds
fix comment, `g3232705` has no meaning here.

2024-02-13 13:19 UTC, tcormackMW commented on CMakeLists.txt
> +# g3232705: Add flag to force non executable stack on gcc builds
fixed

2024-02-13 13:23 UTC, jeffdiclemente commented on CMakeLists.txt
> +# The -Wl,-z noexecstack link option on all gcc builds will
you can build using clang on linux. does this linker option work for clang as well as gcc?

2024-02-14 18:59 UTC, jeffdiclemente approved these changes

2024-02-14 19:30 UTC, merged